  build-tauri:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        # 为 macOS, Windows 和 Android 打包
        platform: [macos-latest, windows-latest, ubuntu-latest]
        # 在矩阵中为 Android 构建定义一个特殊标识
        include:
          - platform: ubuntu-latest
            os: linux # 自定义一个标识，方便后面判断
          - platform: macos-latest
            os: macos
          - platform: windows-latest
            os: windows

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Android 特定的设置步骤 (全新、可靠的方式) ---
      - name: Set up Java
        if: matrix.os == 'linux' # 只在 Android 构建时运行
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Android 开发常用的 JDK 版本

      - name: Setup Android SDK
        if: matrix.os == 'linux'
        uses: android-actions/setup-android@v3
        # 这个 Action 会自动下载命令行工具并设置 ANDROID_HOME

      - name: Install NDK and other components with sdkmanager
        if: matrix.os == 'linux'
        # 注意：这里不再需要 sudo，因为 setup-android action 已经配置好了权限
        run: |
          echo "y" | sdkmanager "ndk;25.2.9519653" "build-tools;34.0.0" "platforms;android-34"
      
      - name: Set NDK_HOME environment variable
        if: matrix.os == 'linux'
        # setup-android 会设置 ANDROID_HOME, 我们需要在此基础上设置 NDK_HOME
        run: echo "NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Decode and place Android signing key
        if: matrix.os == 'linux'
        run: |
          echo "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 --decode > ${{ runner.temp }}/release.keystore
        # 设置环境变量，供 tauri-action 使用
        env:
          TAURI_KEY_PATH: ${{ runner.temp }}/release.keystore
          TAURI_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      # --- 通用的 Rust 和 Node 设置步骤 (保持不变) ---
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install Rust target for Android
        if: matrix.os == 'linux'
        run: rustup target add aarch64-linux-android armv7-linux-androideabi

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install

      # --- 构建步骤 (保持不变) ---
      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 签名密钥的环境变量会自动被 tauri-action 使用
          TAURI_KEY_PATH: ${{ env.TAURI_KEY_PATH }}
          TAURI_KEY_PASSWORD: ${{ env.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}